# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'joy_thief' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for joy_thief
  pod 'Kingfisher', '~> 7.10'

  target 'joy_thiefTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'joy_thiefUITests' do
    # Pods for testing
  end
end 